"""empty message

Revision ID: feb4823b87f3
Revises: ddf11a5ea549
Create Date: 2019-08-03 21:36:27.749269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb4823b87f3'
down_revision = 'ddf11a5ea549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pwd', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pwd')
    # ### end Alembic commands ###
